### ISSUE TITLE
TypeError: environment can only contain strings with Python 3 on Windows

### ISSUE THREAD

**Issue by mrliptontea** [SublimeCodeIntel/CodeIntel#1]
Hi,

First of all, I'm very glad to see this project still live! Keep up the good work. 🥇 

I have an issue to report but luckily also some solutions for it.

## Issue:

Triggering CodeIntel results in an error that I found in `codeintel.log`:

```
Traceback (most recent call last):
  [...]
  File "site-packages\codeintel\codeintel2\lang_php.py", line 980, in _php_info_from_php
    p = process.ProcessOpen(argv, env=env.get_all_envvars())
  File "site-packages\codeintel\process.py", line 581, in __init__
    creationflags=flags)
  File "subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "site-packages\codeintel\process.py", line 399, in _execute_child
    startupinfo)

TypeError: environment can only contain strings
```

My environment:

* Windows 10 64-bit
* Python 3.6.3 64-bit, tried also on Python 3.5 32-bit
* Sublime Text Build 3153 from Dev channel

## Solution

The culprit is this bit of code:

https://github.com/SublimeCodeIntel/CodeIntel/blob/296df71659d38cddb9f47dcd6e517cbebf9ba043/codeintel/process.py#L499-L508

While it is necessary for Python 2, it is breaking in 3 because all keys and values end up being encoded as `bytes`.

I'm not sure what's the best approach here, I came up with:

1. Add `if six.PY2` at line 499
2. Check if `key`/`value` is not `isinstance(value, string_types)` and encode only then.

Similar has been done in https://github.com/django/django/commit/fc6b90bdb7a9531e988245942f79518308616b7b.

**Comment by Kronuz** [comment]
Thank you! This should be fixed now in `v2.0.0-rc.2` 👍
